name: design_system

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter

  shimmer: ^3.0.0
  flutter_svg: ^2.1.0
  figma_squircle: ^0.6.3
  table_calendar: ^3.2.0

dev_dependencies:
  build_runner:
  flutter_gen_runner:
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/Hugeicons/Bulk/Programming Language/
    - assets/Hugeicons/Bulk/Date and Time/
    - assets/Hugeicons/Bulk/Smiley Emojis/
    - assets/Hugeicons/Bulk/Settings/
    - assets/Hugeicons/Bulk/Home/
    - assets/Hugeicons/Bulk/Add Remove Delete/
    - assets/Hugeicons/Bulk/Transportation/
    - assets/Hugeicons/Bulk/Filter Sorting/
    - assets/Hugeicons/Bulk/Layout Borders/
    - assets/Hugeicons/Bulk/Alert Notification/
    - assets/Hugeicons/Bulk/Security/
    - assets/Hugeicons/Bulk/Energy/
    - assets/Hugeicons/Bulk/Geometric Shapes/
    - assets/Hugeicons/Bulk/Food Drinks/
    - assets/Hugeicons/Bulk/Game and Sports/
    - assets/Hugeicons/Bulk/Education/
    - assets/Hugeicons/Bulk/Mouse Cursors/
    - assets/Hugeicons/Bulk/Mathematics/
    - assets/Hugeicons/Bulk/Animation/
    - assets/Hugeicons/Bulk/Furnitures/
    - assets/Hugeicons/Bulk/Check Validation/
    - assets/Hugeicons/Bulk/Bookmark Favorite/
    - assets/Hugeicons/Bulk/Search/
    - assets/Hugeicons/Bulk/Hand Gestures/
    - assets/Hugeicons/Bulk/Dashboard/
    - assets/Hugeicons/Bulk/Image Camera Video/
    - assets/Hugeicons/Bulk/Arrows Round/
    - assets/Hugeicons/Bulk/Edit Formatting/
    - assets/Hugeicons/Bulk/Arrows Sharp/
    - assets/Hugeicons/Bulk/E-Commerce/
    - assets/Hugeicons/Bulk/Login Logout/
    - assets/Hugeicons/Bulk/Users/
    - assets/Hugeicons/Bulk/Medical/
    - assets/Hugeicons/Bulk/Building Landmark Places/
    - assets/Hugeicons/Bulk/Note Task/
    - assets/Hugeicons/Bulk/Location Map/
    - assets/Hugeicons/Bulk/Award Reward/
    - assets/Hugeicons/Bulk/Weather/
    - assets/Hugeicons/Bulk/Cloth Accessories/
    - assets/Hugeicons/Bulk/More Menu/
    - assets/Hugeicons/Bulk/Gym Fitness/
    - assets/Hugeicons/Bulk/Islamic/
    - assets/Hugeicons/Bulk/Kitchen/
    - assets/Hugeicons/Bulk/Legal/
    - assets/Hugeicons/Bulk/Science Technology/
    - assets/Hugeicons/Bulk/Link Unlink/
    - assets/Hugeicons/Bulk/Business and Finance/
    - assets/Hugeicons/Bulk/Presentation/
    - assets/Hugeicons/Bulk/Files Folders/
    - assets/Hugeicons/Bulk/Wifi Signal/
    - assets/Hugeicons/Bulk/Git/
    - assets/Hugeicons/Bulk/Communications/
    - assets/Hugeicons/Bulk/Brand Logo/
    - assets/Hugeicons/Bulk/Download Upload/
    - assets/Hugeicons/Bulk/Hierarchy/
    - assets/Hugeicons/Bulk/Devices/
    - assets/Hugeicons/Bulk/Media/
    - assets/Hugeicons/Twotone/
    - assets/Hugeicons/Twotone/Programming Language/
    - assets/Hugeicons/Twotone/Date and Time/
    - assets/Hugeicons/Twotone/Smiley Emojis/
    - assets/Hugeicons/Twotone/Home/
    - assets/Hugeicons/Twotone/Add Remove Delete/
    - assets/Hugeicons/Twotone/Transportation/
    - assets/Hugeicons/Twotone/Filter Sorting/
    - assets/Hugeicons/Twotone/Layout Borders/
    - assets/Hugeicons/Twotone/Alert Notification/
    - assets/Hugeicons/Twotone/Security/
    - assets/Hugeicons/Twotone/Energy/
    - assets/Hugeicons/Twotone/Edit Formatting/
    - assets/Hugeicons/Twotone/Gym Fitness/
    - assets/Hugeicons/Twotone/Food Drinks/
    - assets/Hugeicons/Twotone/Game and Sports/
    - assets/Hugeicons/Twotone/Education/
    - assets/Hugeicons/Twotone/Mouse Cursors/
    - assets/Hugeicons/Twotone/Mathematics/
    - assets/Hugeicons/Twotone/Animation/
    - assets/Hugeicons/Twotone/Furnitures/
    - assets/Hugeicons/Twotone/Bookmark Favorite/
    - assets/Hugeicons/Twotone/Search/
    - assets/Hugeicons/Twotone/Hand Gestures/
    - assets/Hugeicons/Twotone/Dashboard/
    - assets/Hugeicons/Twotone/Image Camera Video/
    - assets/Hugeicons/Twotone/Arrows Round/
    - assets/Hugeicons/Twotone/Geometric Shapes/
    - assets/Hugeicons/Twotone/Arrows Sharp/
    - assets/Hugeicons/Twotone/E-Commerce/
    - assets/Hugeicons/Twotone/Login Logout/
    - assets/Hugeicons/Twotone/Users/
    - assets/Hugeicons/Twotone/Medical/
    - assets/Hugeicons/Twotone/Building Landmark Places/
    - assets/Hugeicons/Twotone/Note Task/
    - assets/Hugeicons/Twotone/Location Map/
    - assets/Hugeicons/Twotone/Award Reward/
    - assets/Hugeicons/Twotone/Weather/
    - assets/Hugeicons/Twotone/Cloth Accessories/
    - assets/Hugeicons/Twotone/More Menu/
    - assets/Hugeicons/Twotone/Setting/
    - assets/Hugeicons/Twotone/Islamic/
    - assets/Hugeicons/Twotone/Kitchen/
    - assets/Hugeicons/Twotone/Legal/
    - assets/Hugeicons/Twotone/Science Technology/
    - assets/Hugeicons/Twotone/Link Unlink/
    - assets/Hugeicons/Twotone/Business and Finance/
    - assets/Hugeicons/Twotone/Presentation/
    - assets/Hugeicons/Twotone/Files Folders/
    - assets/Hugeicons/Twotone/Wifi Signal/
    - assets/Hugeicons/Twotone/Git/
    - assets/Hugeicons/Twotone/Communications/
    - assets/Hugeicons/Twotone/Check Validation/
    - assets/Hugeicons/Twotone/Brand Logo/
    - assets/Hugeicons/Twotone/Download Upload/
    - assets/Hugeicons/Twotone/Hierarchy/
    - assets/Hugeicons/Twotone/Devices/
    - assets/Hugeicons/Twotone/Media/
    - assets/Hugeicons/Stroke/
    - assets/Hugeicons/Stroke/Programming Language/
    - assets/Hugeicons/Stroke/Date and Time/
    - assets/Hugeicons/Stroke/Smiley emojis/
    - assets/Hugeicons/Stroke/Settings/
    - assets/Hugeicons/Stroke/Home/
    - assets/Hugeicons/Stroke/Add Remove Delete/
    - assets/Hugeicons/Stroke/Transportation/
    - assets/Hugeicons/Stroke/Filter Sorting/
    - assets/Hugeicons/Stroke/Layout Borders/
    - assets/Hugeicons/Stroke/Alert Notification/
    - assets/Hugeicons/Stroke/Security/
    - assets/Hugeicons/Stroke/Energy/
    - assets/Hugeicons/Stroke/Geometric Shapes/
    - assets/Hugeicons/Stroke/Food Drinks/
    - assets/Hugeicons/Stroke/Game and Sports/
    - assets/Hugeicons/Stroke/Education/
    - assets/Hugeicons/Stroke/Mouse Cursors/
    - assets/Hugeicons/Stroke/Mathematics/
    - assets/Hugeicons/Stroke/Animation/
    - assets/Hugeicons/Stroke/Furnitures/
    - assets/Hugeicons/Stroke/Check Validation/
    - assets/Hugeicons/Stroke/Bookmark Favorite/
    - assets/Hugeicons/Stroke/Search/
    - assets/Hugeicons/Stroke/Hand Gestures/
    - assets/Hugeicons/Stroke/Dashboard/
    - assets/Hugeicons/Stroke/Image Camera Video/
    - assets/Hugeicons/Stroke/Arrows Round/
    - assets/Hugeicons/Stroke/Edit Formatting/
    - assets/Hugeicons/Stroke/Arrows Sharp/
    - assets/Hugeicons/Stroke/E-Commerce/
    - assets/Hugeicons/Stroke/Login Logout/
    - assets/Hugeicons/Stroke/Users/
    - assets/Hugeicons/Stroke/Medical/
    - assets/Hugeicons/Stroke/Building Landmark Places/
    - assets/Hugeicons/Stroke/Note task/
    - assets/Hugeicons/Stroke/Location Map/
    - assets/Hugeicons/Stroke/Award Reward/
    - assets/Hugeicons/Stroke/Weather/
    - assets/Hugeicons/Stroke/Cloth Accessories/
    - assets/Hugeicons/Stroke/More Menu/
    - assets/Hugeicons/Stroke/Gym Fitness/
    - assets/Hugeicons/Stroke/Islamic/
    - assets/Hugeicons/Stroke/Kitchen/
    - assets/Hugeicons/Stroke/Legal/
    - assets/Hugeicons/Stroke/Science technology/
    - assets/Hugeicons/Stroke/Link Unlink/
    - assets/Hugeicons/Stroke/Business and Finance/
    - assets/Hugeicons/Stroke/Presentation/
    - assets/Hugeicons/Stroke/Files Folders/
    - assets/Hugeicons/Stroke/Wifi Signal/
    - assets/Hugeicons/Stroke/Git/
    - assets/Hugeicons/Stroke/Communications/
    - assets/Hugeicons/Stroke/Brand Logo/
    - assets/Hugeicons/Stroke/Download Upload/
    - assets/Hugeicons/Stroke/Hierarchy/
    - assets/Hugeicons/Stroke/Devices/
    - assets/Hugeicons/Stroke/Media/
    - assets/Hugeicons/Solid/
    - assets/Hugeicons/Solid/Programming Language/
    - assets/Hugeicons/Solid/Date and Time/
    - assets/Hugeicons/Solid/Smiley Emojis/
    - assets/Hugeicons/Solid/Settings/
    - assets/Hugeicons/Solid/Home/
    - assets/Hugeicons/Solid/Add Remove Delete/
    - assets/Hugeicons/Solid/Transportation/
    - assets/Hugeicons/Solid/Filter Sorting/
    - assets/Hugeicons/Solid/Layout Borders/
    - assets/Hugeicons/Solid/Alert Notification/
    - assets/Hugeicons/Solid/Security/
    - assets/Hugeicons/Solid/Energy/
    - assets/Hugeicons/Solid/Geometric Shapes/
    - assets/Hugeicons/Solid/Food Drinks/
    - assets/Hugeicons/Solid/Game and Sports/
    - assets/Hugeicons/Solid/Education/
    - assets/Hugeicons/Solid/Mouse Cursors/
    - assets/Hugeicons/Solid/Mathematics/
    - assets/Hugeicons/Solid/Animation/
    - assets/Hugeicons/Solid/Furnitures/
    - assets/Hugeicons/Solid/Check Validation/
    - assets/Hugeicons/Solid/Bookmark Favorite/
    - assets/Hugeicons/Solid/Search/
    - assets/Hugeicons/Solid/Hand Gestures/
    - assets/Hugeicons/Solid/Dashboard/
    - assets/Hugeicons/Solid/Image Camera Video/
    - assets/Hugeicons/Solid/Arrows Round/
    - assets/Hugeicons/Solid/Edit Formatting/
    - assets/Hugeicons/Solid/Arrows Sharp/
    - assets/Hugeicons/Solid/E-Commerce/
    - assets/Hugeicons/Solid/Login Logout/
    - assets/Hugeicons/Solid/Users/
    - assets/Hugeicons/Solid/Medical/
    - assets/Hugeicons/Solid/Building Landmark Places/
    - assets/Hugeicons/Solid/Note Task/
    - assets/Hugeicons/Solid/Location Map/
    - assets/Hugeicons/Solid/Award Reward/
    - assets/Hugeicons/Solid/Weather/
    - assets/Hugeicons/Solid/Cloth Accessories/
    - assets/Hugeicons/Solid/More Menu/
    - assets/Hugeicons/Solid/Gym Fitness/
    - assets/Hugeicons/Solid/Islamic/
    - assets/Hugeicons/Solid/Kitchen/
    - assets/Hugeicons/Solid/Legal/
    - assets/Hugeicons/Solid/Science Technology/
    - assets/Hugeicons/Solid/Link Unlink/
    - assets/Hugeicons/Solid/Business and Finance/
    - assets/Hugeicons/Solid/Presentation/
    - assets/Hugeicons/Solid/Files Folders/
    - assets/Hugeicons/Solid/Wifi Signal/
    - assets/Hugeicons/Solid/Git/
    - assets/Hugeicons/Solid/Communications/
    - assets/Hugeicons/Solid/Brand Logo/
    - assets/Hugeicons/Solid/Download Upload/
    - assets/Hugeicons/Solid/Hierarchy/
    - assets/Hugeicons/Solid/Devices/
    - assets/Hugeicons/Solid/Media/
    - assets/Hugeicons/Duotone/
    - assets/Hugeicons/Duotone/Programming Language/
    - assets/Hugeicons/Duotone/Date and Time/
    - assets/Hugeicons/Duotone/Smiley Emojis/
    - assets/Hugeicons/Duotone/Settings/
    - assets/Hugeicons/Duotone/Home/
    - assets/Hugeicons/Duotone/Add Remove Delete/
    - assets/Hugeicons/Duotone/Transportation/
    - assets/Hugeicons/Duotone/Filter Sorting/
    - assets/Hugeicons/Duotone/Layout Borders/
    - assets/Hugeicons/Duotone/Alert Notification/
    - assets/Hugeicons/Duotone/Security/
    - assets/Hugeicons/Duotone/Energy/
    - assets/Hugeicons/Duotone/Geometric Shapes/
    - assets/Hugeicons/Duotone/Food Drinks/
    - assets/Hugeicons/Duotone/Game and Sports/
    - assets/Hugeicons/Duotone/Education/
    - assets/Hugeicons/Duotone/Mouse Cursors/
    - assets/Hugeicons/Duotone/Mathematics/
    - assets/Hugeicons/Duotone/Animation/
    - assets/Hugeicons/Duotone/Furnitures/
    - assets/Hugeicons/Duotone/Check Validation/
    - assets/Hugeicons/Duotone/Bookmark Favorite/
    - assets/Hugeicons/Duotone/Search/
    - assets/Hugeicons/Duotone/Hand Gestures/
    - assets/Hugeicons/Duotone/Dashboard/
    - assets/Hugeicons/Duotone/Image Camera Video/
    - assets/Hugeicons/Duotone/Arrows Round/
    - assets/Hugeicons/Duotone/Edit Formatting/
    - assets/Hugeicons/Duotone/Arrows Sharp/
    - assets/Hugeicons/Duotone/E-Commerce/
    - assets/Hugeicons/Duotone/Login Logout/
    - assets/Hugeicons/Duotone/Users/
    - assets/Hugeicons/Duotone/Medical/
    - assets/Hugeicons/Duotone/Building Landmark Places/
    - assets/Hugeicons/Duotone/Note Task/
    - assets/Hugeicons/Duotone/Location Map/
    - assets/Hugeicons/Duotone/Award Reward/
    - assets/Hugeicons/Duotone/Weather/
    - assets/Hugeicons/Duotone/Cloth Accessories/
    - assets/Hugeicons/Duotone/More Menu/
    - assets/Hugeicons/Duotone/Gym Fitness/
    - assets/Hugeicons/Duotone/Islamic/
    - assets/Hugeicons/Duotone/Kitchen/
    - assets/Hugeicons/Duotone/Legal/
    - assets/Hugeicons/Duotone/Science Technology/
    - assets/Hugeicons/Duotone/Link Unlink/
    - assets/Hugeicons/Duotone/Business and Finance/
    - assets/Hugeicons/Duotone/Presentation/
    - assets/Hugeicons/Duotone/Files Folders/
    - assets/Hugeicons/Duotone/Wifi Signal/
    - assets/Hugeicons/Duotone/Git/
    - assets/Hugeicons/Duotone/Communications/
    - assets/Hugeicons/Duotone/Brand Logo/
    - assets/Hugeicons/Duotone/Download Upload/
    - assets/Hugeicons/Duotone/Hierarchy/
    - assets/Hugeicons/Duotone/Devices/
    - assets/Hugeicons/Duotone/Media/

flutter_gen:
  output: lib/
  integrations:
    image: false
    flutter_svg: false
    rive: false
    lottie: false
